vanvalenlab/deepcell-tracking

.travis.yml
deepcell_tracking/__init__.py
deepcell_tracking/tracking.py
deepcell_tracking/tracking_test.py
deepcell_tracking/utils.py
deepcell_tracking/utils_test.py
setup.py

The `CellTracker` makes far too many `get_features` calls.  By using dynamic programming, and caching each set of features, we can greatly reduce the time to track cells.  Lots of other refactoring went into these changes, including:
* Adding a logger instead of print.
* DRY out the `fetch` functions.
* Replace `feature_shape` dictionary with `get_feature_shape` method.
* Add all features to new track OUTSIDE of `create_new_track`.
* Replace `compute_feature` with `compute_distance` as it was not useful for any other feature.
* Split out `_get_cost_matrix` into several helper functions including `_build_cost_matrix` and `_get_input_pairs`.
* Add utils.resize to replace the skimage/cv2 differences.
* `get_features` is hard-coded for `self.x` and `self.y` and no longer accepts lists of …

Refactor CellTracker with dynamic programming!

---

deepcell_tracking/isbi_utils.py
deepcell_tracking/isbi_utils_test.py
deepcell_tracking/tracking.py
deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

* Moved `clean_up_annotations` to `utils.py` to more easily import and use it elsewhere.
* Convert Graphs to DiGraphs to clearly differentiate between parents and daughters to define a correct division node.
* Added `trk_to_isbi` to easily create the ISBI txt files.
* Fixed bug in `txt_to_graph` that allowed parents to exist in a frame that is not the previous frame.
* Fixed bug in `contig_tracks` that did not properly match parents and daughters between "new" contiguous tracks.
* Improve test coverage for `isbi_utils`
* Updated `CellTracker._get_cost_matrix` to use `tuple` instead of `list (Fixes #16)

Fixed lineage bug in ISBI formatted txt files

---

.coveragerc
README.md
deepcell_tracking/tracking.py
deepcell_tracking/tracking_test.py
deepcell_tracking/utils_test.py

Add tests for `dump()` and DRY out `postprocess` by calling `dump`.
Add inner function `_track_frame` called on every frame inside the `track_cells` loop.  This way it is easier to modify the code and call `model.progress` in each loop.
Update the coverage requirement to 75%.
Fixes #21

Create inner _track_frame function and improve test coverage.

---

requirements.txt
setup.py

From the `opencv-python-headless` README:
> Packages for server (headless) environments (such as Docker, cloud environments etc.), no GUI library dependencies
> 
> These packages are smaller than the two other packages above because they do not contain any GUI functionality (not compiled with Qt / other GUI components). This means that the packages avoid a heavy dependency chain to X11 libraries and you will have for example smaller Docker images as a result. **You should always use these packages if you do not use cv2.imshow et al. or you are using some other package (such as PyQt) than OpenCV to create your GUI**.
Since we only use `cv2` for resizing images, we should use the headless build.

Use headless builds of OpenCV

---

.github/workflows/tests.yaml
README.md
requirements-test.txt
requirements.txt
setup.py

[Environment markers](https://www.python.org/dev/peps/pep-0508/#environment-markers) allow `pip` to dynamically install the appropriate version of a package for different versions of Python. While this is not an issue for most dependencies (`scipy`, `numpy`, etc.), `opencv-python-headless` will attempt to install the latest version of the package even for unsupported Python versions.
This PR removes `requirements.txt` and `requirements-test.txt` in favor of using `setup.py`, where we can set the version of `opencv-python-headless` for each Python version.

Use environment markers in setup.py to conditionally change opencv versions

---

.github/workflows/tests.yaml

Use GitHub Actions build matrix to run tests for Ubuntu, Windows, and MacOS.

Run tests against each OS version.

---

deepcell_tracking/isbi_utils_test.py
deepcell_tracking/tracking.py
deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

On Windows, the `tempfile.NamedTemporaryFile` cannot be opened while it is currently open (which is not an issue on macOS/Ubuntu).
In our tests, `save_trks`, and `tracker.dump`, we create a `NamedTemporaryFile` and try to add it to the tarfile. Internally in `tarfile.add`, the `NamedTemporaryFile` is opened again, causing an `IOError` in Windows.
To avoid this, the tests have been replaced with the testing fixture `tmpdir`, and both `save_trks` and `.dump` have been updated to use `NamedTemporaryFile(delete=False)` and manually closing and deleting the file.
While this is not ideal, I cannot find another workaround to prevent this issue on Windows.
---
Additionally, some other tests have been updated to use `os.linesep` instead of the `\n` character.

Use tmpdir test fixture instead of NamedTemporaryFile for Windows compatibility.

---

.github/workflows/tests.yaml

Split out each coverage report by OS and python version, instead of collapsing into the same coverage report for all OS versions.

Use each coveralls key with os and python versions.

---

.github/workflows/tests.yaml

This is a new feature that did not work when the project first migrated to GitHub Actions.

Split PyTest and Coveralls into separate steps.

---

.github/workflows/tests.yaml

Forked repositories will not have access to `COVERALLS_REPO_TOKEN`, and the tests will not run due to a filed Coveralls step. Instead, conditionally run the Coveralls step only if `COVERALLS_REPO_TOKEN` is set.

Only run Coveralls if COVERALLS_REPO_TOKEN is set.

---

deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

In clean_up_annotations(), transform y to int32 at the beginning to avoid overflow when applying new uids to the original matrix.

transform dtype early

---

deepcell_tracking/tracking.py
setup.py

Change the `<17` version restriction for `scikit-image` to `>=0.14.5` as it is unnecessarily limiting for other projects using `deepcell-tracking`, and the breaking changes in .17+ are not relevant.
Additionally, remove the deprecated `coordinates="rc"` from `regionprops` calls.

Remove scikit-image version restriction.

---

.coveragerc
deepcell_tracking/tracking.py

Using the track_id and cell_id from current & future embeddings was behaving weirdly. This PR attempts to fix it by:
- Setting `idx_to_id` as a map of `{(frame, cell_idx): cell_id}`
- Update the loop in `_get_parent` to loop over the size of the `predictions` array, and use the current index and frame to look up the cell_id using `idx_to_id`.
- Remove the track_id loop entirely because `track_idx == track_id`.

Fix predictions-slicing useing idx_to_id in _get_parent.

---

deepcell_tracking/tracking.py
deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

Previously, the appearance (and all other features) had a shape of:
```
(batch, maxObjects, frames, appearance_dim, appearance_dim, channels)
```
But the neighborhood encoder requires inputs with the time dimension first (in order to keep each frame independent of each other).
This PR updates all input and output arrays to expect the time axis to be first, as the neighborhood encoder requires. The new appearance shape is:
```
(batch, frames, maxObjects, appearance_dim, appearance_dim, channels)
```

Change shape of feature arrays to use time as the first axis.

---

setup.py

This PR bumps the `deepcell-toolbox` dependency to 0.10.0.

Bump deepcell-toolbox to 0.10.x

---

deepcell_tracking/tracking.py
deepcell_tracking/tracking_test.py
deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

The third time's the charm! This is the same PR as #63, but removing the changes featured in #62.
This PR changes the writemode of `tarfile` to write in `w:gz`, or with gzip compression. The read mode of `tarfile` natively supports this.
Additionally, some related tests have been updated to use the `tmpdir` test fixture instead of creating their own temporary directory.

Compress `.trks` by using gzip compression when writing the tarfile.

---

deepcell_tracking/isbi_utils.py
deepcell_tracking/isbi_utils_test.py
setup.py

* Replace writing to GT and result ISBI-style .txt files with saving an array of ISBI-style dictionaries and comparing those.
* Modifying `isbi_utils_tests` to test the new approach
* Comparing in memory is quicker and allows for less chances of error

Change `isbi_utils` from writing files to comparing in memory

---

deepcell_tracking/tracking.py
deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

In the `data-registry`, we often read and write track data in memory in order to facilitate moving data to and from s3 buckets. This PR enables a `io.BytesIO()` object to be passed into `save_trks` and `load_trks` in place of a filepath. Additionally a new utility function `save_track_data` is introduced to serve as a base for `save_trks` and `save_trk` which are wrappers that allow saving to either `trk` or `trks`.

Support saving and loading trk/trks data to/from `BytesIO`

---

deepcell_tracking/utils.py
deepcell_tracking/utils_test.py
setup.py

If a cell's daughter ID is not a valid track ID, then `is_valid_lineage` will crash due to a `KeyError`. Instead, it should catch this error and note the lineage as invalid.

`is_valid_lineage` should check if the daughter ID is valid.

---

deepcell_tracking/utils.py
setup.py

#73 updated `is_valid_lineage` to do better of all cells. However, there is no extra validation of the `parent` field, which is used in the `isbi_utils` functions.
This PR adds some basic validation of the `parent` lineage field to improve the validation of the lineage objects.

Validate parent lineage field as well as daughters.

---

deepcell_tracking/utils.py
setup.py

There is a bad label in one of the parent checks. This PR updates the message for accuracy.

Fix bad warning message in `is_valid_lineage`

---

pytest.ini
setup.py

Tests started failing due to a duplicate test event found in the `build` directory. This should be ignored in `pytest.ini`, but is an erroneous comma in the path. This PR fixes the `norecursedirs` setting.

Fix `norecursedirs` to ignore build directory

---

deepcell_tracking/utils.py
deepcell_tracking/utils_test.py
setup.py

No need to check if the daughters are in `all_cells`, as we check that for each lineage. Just check that the daughter is in the lineage.
Don't return False as a shortcut, just warn and continue to the next label. This will enable all warnings to be shown.

Fix bug in `is_valid_lineage`; daughters can be < parent.

---

deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

The `trk_stats` function originally printed stats, but did not return them to the user. This PR updates the function to return a dictionary of statistics and makes it possible to input `X`, `y` and `lineages` instead of loading the data from `filename`.

Update `utils.trk_stats` to return a dictionary of stats as output

---

deepcell_tracking/isbi_utils.py
deepcell_tracking/isbi_utils_test.py
setup.py

Addresses #91 and bumps version to 0.5.6 for the next patch release after this PR is complete. I tested the new functionality in the model-registry and those updates can be seen in this branch: https://github.com/vanvalenlab/model-registry/compare/mrgn/tracking-evaluation. I added rounding after running this test, but decimals will now be truncated to 2 digits.

Add additional metrics to report in classify_divisions

---

.github/workflows/tests.yaml
setup.py

Updates deepcell-toolbox to ~=0.11.2.

Drop support for python 3.6 and bump deepcell-toolbox requirement

---

deepcell_tracking/utils.py
deepcell_tracking/utils_test.py

Add a flag to get_image_features to allow for doing fixed sized crops rather than crop and resize.
Crop and resize removes information about cell size, which is useful for cell tracking and also learning dynamic representations of cell behavior.

Enable option for fixed size crops in get_image_features

---

deepcell_tracking/isbi_utils.py
deepcell_tracking/metrics.py
deepcell_tracking/metrics_test.py
deepcell_tracking/test_utils.py

Recent reviews of tracking predictions have identified a failure mode in the current metrics packages. Different segmentation predictions can sometimes lead to a cell dividing in one frame before or after the frame assigned to the division in the ground truth. Currently this leads to that division counting as both a false positive and a missed division. This PR introduces a new metrics function that identifies these events and corrects the metrics to classify this division as correct. Additionally a new metrics class for tracking (`TrackingMetrics`) has been introduced to coordinate running all of the necessary metrics functions.
In the current test split, applying the new metrics pipeline led to the following changes in metrics:
| Metric                        | Old  | New  | …

Classify divisions that are +/- 1 frame as correct

---

deepcell_tracking/metrics.py
deepcell_tracking/metrics_test.py
setup.py

Different key names were used in `correct_shifted_divisions` which caused issues in some downstream analyses in the model-registry. This PR standardizes all keys in the metrics package to avoid confusion.

Correct keys in correct_shifted_divisions

---

deepcell_tracking/isbi_utils.py
deepcell_tracking/isbi_utils_test.py
deepcell_tracking/metrics.py

This addition to the metrics package makes it possible to directly input ISBI style outputs into our metrics pipeline. This simplifies the process of benchmarking against competitor models which tend to output ISBI style tracks.

Add support for ISBI inputs to the metrics package

---

setup.py

A patch release to upper-bound numpy to prevent errors related to expired scalar deprecations. Bumps the `deepcell-toolbox` dependency as well, which already has more comprehensive fixes for this issue.

REL: pin numpy and update deepcell-toolbox dependency

---

deepcell_tracking/utils.py

This PR fixes a bug in `get_image_features`. If the X data is passed in with an integer type (instead of float), the output of `crop_mode='fixed'` and `norm=True` is incorrect. In the examples below, the first image is incorrect while the second is correct.
This PR eliminates the bug by casting X data to float32 and y data to int32 to avoid incorrect use of the function.

Cast data to correct type in `get_image_features`

---

deepcell_tracking/utils.py

A minor change that should improve performance. Unfortunately NumPy isn't smart enough to cache indexing results for reuse, so each `app[idx]` invocation of advanced indexing is actually creating a new array (as opposed to a view), resulting in both more memory usage and additional computation time for each allocation. There should be a significant performance boost by only performing the advanced indexing operation once and reusing the result.
Not critically important - just something I noticed while reviewing #114!

Reuse indexed array to avoid extra array copies.

---

.github/workflows/pypi.yaml
.github/workflows/tests.yaml

Bump action versions to keep CI current, c.f. https://github.com/vanvalenlab/deepcell-tf/pull/653

Bump default action versions.

---

.github/workflows/pypi.yaml

- Pin Python version to 3.10
- Explicitly add setuptools and wheel to build env
- Bump action versions

Update action for deploying to pypi
